name: Delete Lambda Function

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  delete:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us-east-1, ap-south-1]  # Add more if needed

    steps:
    - name: Set up AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ matrix.region }}

    - name: Delete Lambda Function
      continue-on-error: true  # Prevent failure if function doesn't exist
      run: |
        FUNCTION_NAME=arithmetic-lambda
        echo "Deleting Lambda $FUNCTION_NAME in ${{ matrix.region }}"
        aws lambda delete-function --function-name $FUNCTION_NAME
